id = "helios-zed-theme"
name = "Helios Zed Theme"
description = "Helios theme for Zed"
version = "0.0.3"
schema_version = 2
authors = ["<chris@puska.org>"]
repository = "https://github.com/heliosgraphics/helios-zed-theme"
